# database configration
spring.datasource.url=jdbc:mysql://localhost:3306/blood_donor_db
spring.datasource.username=root
spring.datasource.password=Ankit9119028638
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.application.name=Blood-Donor-Finder
server.port=8080


jwt.secret=ThisIsAVerySecretKeyForBloodDonorFinderApp2024
jwt.expiration=86400000


# email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=allbytes1234@gmail.com
spring.mail.password=aszv kyae cbbh ubsw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.security.user.name=admin
spring.security.user.password=admin

# Redis Config
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

# swagger UI
# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
